# Generated by Django 2.2.6 on 2020-06-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20200622_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
        ),
    ]
