# Generated by Django 2.2.6 on 2020-06-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20200624_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_name', models.TextField(verbose_name='Название издательства')),
                ('make_country', models.CharField(max_length=2, verbose_name='Страна издательства')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_maker', to='p_library.Book', verbose_name='Книга')),
            ],
        ),
    ]
