# Generated by Django 2.2.6 on 2020-06-26 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_maker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maker',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='maker_n',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='make_nam', to='p_library.Maker', verbose_name='Издательство'),
            preserve_default=False,
        ),
    ]
