# Generated by Django 2.2.6 on 2020-06-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0007_auto_20200626_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='maker_n',
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book_publish', to='p_library.Maker', verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='make_name',
            field=models.TextField(default=None, verbose_name='Название издательства'),
        ),
    ]
