# Generated by Django 2.2.6 on 2020-06-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_auto_20200626_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publish',
        ),
    ]
