# Generated by Django 2.2.6 on 2020-06-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0010_book_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish',
            new_name='maker',
        ),
        migrations.AddField(
            model_name='maker',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='publish_house', to='p_library.Book', verbose_name='Издательство'),
        ),
    ]
