# Generated by Django 2.2.6 on 2020-06-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0011_auto_20200628_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='maker',
        ),
    ]
