# Generated by Django 2.2.6 on 2020-06-28 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0013_auto_20200628_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='publish_house', to='p_library.Book', verbose_name='Издательство')),
                ('publisher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='publish_house', to='p_library.Maker', verbose_name='Издательство')),
            ],
        ),
    ]
