# Generated by Django 2.2.6 on 2020-06-28 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0014_bookmaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmaker',
            name='year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='publish_year', to='p_library.Book', verbose_name='Год издания'),
        ),
    ]
