# Generated by Django 2.2.6 on 2020-06-28 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0015_bookmaker_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='maker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book_publisher', to='p_library.Maker', verbose_name='Издательство'),
        ),
    ]
