# Generated by Django 2.2.6 on 2020-06-28 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0016_auto_20200628_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='maker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book_pub', to='p_library.Maker', verbose_name='Издательство'),
        ),
    ]
