# Generated by Django 2.2.6 on 2020-07-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0019_friend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ['friend_name']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='maker',
        ),
        migrations.AddField(
            model_name='book',
            name='friend_reader',
            field=models.ManyToManyField(blank=True, related_name='book_reader', to='p_library.Friend', verbose_name='Читающие друзья'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='p_library.Maker', verbose_name='Издатель'),
        ),
        migrations.AlterField(
            model_name='book',
            name='copy_count',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_release',
            field=models.SmallIntegerField(verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='bookmaker',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='p_library.Maker', verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='book',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='p_library.Book', verbose_name='Книги'),
        ),
    ]
