# Generated by Django 2.2.6 on 2020-07-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0020_auto_20200706_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user_avatars/%Y/%m/%d'),
        ),
    ]
