# Generated by Django 2.2.6 on 2020-07-12 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0021_book_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='book',
            new_name='friend_book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='friend_reader',
        ),
        migrations.AddField(
            model_name='book',
            name='friend_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='p_library.Friend', verbose_name='Читающий друг'),
        ),
        migrations.AlterField(
            model_name='book',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d '),
        ),
    ]
