# Generated by Django 2.2.6 on 2020-07-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0022_auto_20200712_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmaker',
            options={'ordering': ['publisher']},
        ),
    ]
